include:
  - project: 'MicroService/ci-template'
    file: '/.gitlab-ci-module-be-template.yml'
#    file: '/.gitlab-ci-module-be-join-template.yml'
variables:
  # 用户名
  SSH_USERNAME: root
  # 密码
  SSH_PASSWORD: Rj@002474
  # 主机
  SSH_HOST: 192.168.0.86
  # 端口
  SSH_PORT: 22
  # 运行模块
  RUNNING_MODULE: rjegov-journal-service
  # 项目模块名称
  MODULE_NAME: rjegov-journal
  # 接收地址
  PROJECT_PATH: /home/rjsoft/cloud-platform/running
  # 运行端口
  RUNNING_PORT: 7908
  # 运行激活
  ACTIVE_PROFILE: test
  # JVM选项
  JVM_OPTIONS: -Xmx200m -Xms150m
  # 只有该命名空间下才会构建，用户名或者组名
  ONLY_NAMESPACE: rjegov80
  # 只有该分支的提交才会构建
  ONLY_REF: master
