spring:
  profiles:
    active: default
  config:
    location: http://192.168.0.42/zhuanglw/config/raw/master/rjegov80/common.sec
  application:
    name: journal
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
server:
  max-http-header-size: 256KB
rongji:
  module:
    journal:
      excel-path: ./temp
      managers:
        - journal_manager
        - sys_manager
    redis-prefix-key: "journal:doc:acl:user:"
    redis-expire-timeout: 15
    redis-expire-time-unit: minutes
---
spring:
  profiles: dev
#  datasource-multi-mapper-pointcut: execution(* com.rongji.egov.mybatis.base.mapper.*Mapper.*(..))
  datasource-multi-enable: true
#  datasource-multi-default-holder: ROOT
#eureka:
#  instance:
#    metadata-map:
#      appProvider: true
#      #      private: true
#      zone: lwjhn-dev # 区域名 随便起一个，不要直接在这复制
#      invisible: DIFF_ZONE # 不同区域间的服务不可见（仅本区域可见）
logging:
  level:
    com.rongji.egov: debug
server:
  port: 7909
---
spring:
  profiles: test
  config:
    location: ../common.sec
server:
  port: 7908
